# Generated by Django 4.2 on 2023-05-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.FloatField(),
        ),
    ]
