# Generated by Django 4.2 on 2023-05-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='enumerate',
            new_name='email',
        ),
    ]
