# Generated by Django 4.2 on 2023-05-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_enumerate_commande_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.JSONField(),
        ),
    ]
