# Generated by Django 4.2 on 2023-05-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_commande_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.CharField(max_length=500),
        ),
    ]
